name: Tests CI

on:
  workflow_dispatch:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-verison: '11'
          distribution: 'adopt'
      - name: "run test"
        run: mvn test
